up:
	docker compose up --build -d

up_logs:
	docker compose up --build 

down:
	docker compose down

logs:
	docker compose logs -f

restart:
	docker compose down && docker compose up --build -d

restart_logs:
	docker compose down && docker compose up --build
